baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# 如果想要让官方的这个示例主题被显示，需要删除 layouts/index.html 文件
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[module]
proxy = 'https://goproxy.cn,https://goproxy.io,direct'