baseURL = 'http://hugo-demo.102205.xyz/'
languageCode = 'zh-cn'
title = '我的 Hugo 站点'
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[module]
proxy = 'https://goproxy.cn,https://goproxy.io,direct'
