# Language configuration

[cn]
languageName ="中文"
contentDir = "content/cn"
weight = 2
[cn.params]
title = "中文文档"
description = "Docsy 示例站点"

[en]
languageName ="English"
contentDir = "content/en"
# Weight used for sorting.
weight = 1
[en.params]
title = "Goldydocs"
description = "A Docsy example site"

[no]
languageName ="Norsk"
contentDir = "content/no"
[no.params]
title = "Goldydocs"
description = "Docsy er operativsystem for skyen"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"

[fa]
languageName ="فارسی"
contentDir = "content/fa"
[fa.params]
title = "اسناد گلدی"
description = "یک نمونه برای پوسته داکسی"
time_format_default = "2006.01.02"
time_format_blog = "2006.01.02"
