# 当一个文件的名称或者文件所在目录的名称包含中文时，无法显示末尾的最后编辑时间。
# https://github.com/peaceiris/actions-hugo/issues/496
date = ['date', 'publishDate', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
# lastmod = ["date", ":filename", "publishDate", "lastmod"]
# lastmod = [':fileModTime']
publishDate = ['publishDate', 'date']