# Language configuration

[cn]
title = "中文文档"
description = "Docsy 示例站点"
languageName ="中文"
contentDir = "content/cn"
weight = 2

[en]
title = "Goldydocs"
description = "A Docsy example site"
languageName ="English"
contentDir = "content/en"
# Weight used for sorting.
weight = 1

[no]
title = "Goldydocs"
description = "Docsy er operativsystem for skyen"
languageName ="Norsk"
contentDir = "content/no"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"

[fa]
title = "اسناد گلدی"
description = "یک نمونه برای پوسته داکسی"
languageName ="فارسی"
contentDir = "content/fa"
time_format_default = "2006.01.02"
time_format_blog = "2006.01.02"